# Generated by Django 5.0.1 on 2024-02-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_categoryproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryProduct',
        ),
        migrations.AddField(
            model_name='products',
            name='availability2',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
    ]
