# Generated by Django 5.0.1 on 2024-02-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_categoryproduct_remove_products_availability2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
    ]
